app:
  name: ads
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: notsecure
rabbitmq:
  consumer_pool: 10
pagination:
  page_size: 10
logger:
  path: log/app.log
  level: info
